version: "3.3"
services:
    db:
        image: mongo:latest
        environment: 
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: criscats
        ports:
            - 27017:27017
        volumes:
            - data:/data/db

volumes:
    data: